#!/bin/bash

if [ -z $ACTIVE_REPO ]
then
    echo "Error: \$ACTIVE_REPO environment variable not set"
    exit 1
fi

if [ -z $TURING_HOME ]
then
    echo "Error: \$TURING_HOME environment variable not set"
    exit 1
fi

canvas_path="${ACTIVE_REPO}/src/app2/turingcanvas"
server_path="${ACTIVE_REPO}/src/app2/server"
frontend_path="${ACTIVE_REPO}/src/app2/frontend"

echo "- Building Turing web server at '${server_path}'"
cd "${server_path}" && bun i

echo "- Building Turing canvas at '${canvas_path}'"
cd "${canvas_path}" && bun i && bun run build

echo "- Building Turing App at    '${frontend_path}'"
cd "${frontend_path}" && bun i && bun run build

echo "- Installing..."
cmake --install "${TURING_HOME}/../build_package" --component app | head -n 1


