#!/usr/bin/env bash
#
# install.sh — register the `turingdb://` URL handler on macOS and Linux.
#
# After installing, clicking `turingdb://start?port=6666` in a browser will
# launch the local `turingdb` binary. The visualizer's Databases panel uses
# this to spawn a local instance with no manual terminal work from the user.
#
# Requirements:
#   - A `turingdb` binary on $PATH, or TURINGDB_BIN pointing to one.
#
# Usage:
#   ./install.sh                 # install
#   ./install.sh --uninstall     # remove the handler
#

set -euo pipefail

SCHEME="turingdb"
APP_NAME="TuringDB"
BUNDLE_ID="bio.turing.db.launcher"

PREFIX="${PREFIX:-$HOME/.local/share/turingdb}"
LAUNCHER="$PREFIX/turingdb-launcher.sh"

UNINSTALL=0
if [[ "${1:-}" == "--uninstall" ]]; then
  UNINSTALL=1
fi

log()  { printf '  %s\n' "$*"; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

resolve_turingdb_bin() {
  if [[ -n "${TURINGDB_BIN:-}" ]]; then
    [[ -x "$TURINGDB_BIN" ]] || die "TURINGDB_BIN=$TURINGDB_BIN is not executable"
    printf '%s' "$TURINGDB_BIN"
    return
  fi
  local found
  if found=$(command -v turingdb 2>/dev/null); then
    printf '%s' "$found"
    return
  fi
  die "no 'turingdb' binary found on PATH. Install it first, or set TURINGDB_BIN."
}

write_launcher() {
  local bin="$1"
  mkdir -p "$PREFIX"
  cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# Auto-generated by install.sh. Invoked by the OS when a turingdb:// URL is
# opened. Parses the URL's query string and starts the TuringDB server.
set -euo pipefail

URL="\${1:-}"
[[ -n "\$URL" ]] || exit 0

# Parse "turingdb://<action>?key=val&key=val"
rest="\${URL#${SCHEME}://}"
action="\${rest%%\?*}"
query=""
if [[ "\$rest" == *\?* ]]; then
  query="\${rest#*\?}"
fi

# Default args
port=6666
graph=""

IFS='&' read -ra parts <<< "\$query"
for kv in "\${parts[@]}"; do
  [[ -z "\$kv" ]] && continue
  k="\${kv%%=*}"
  v="\${kv#*=}"
  # URL-decode %XX sequences
  v=\$(printf '%b' "\${v//%/\\\\x}")
  case "\$k" in
    port)  port="\$v" ;;
    graph) graph="\$v" ;;
  esac
done

BIN="${bin}"
LOG_DIR="\$HOME/.local/share/turingdb/logs"
mkdir -p "\$LOG_DIR"
LOG_FILE="\$LOG_DIR/turingdb-\$(date +%Y%m%d-%H%M%S).log"

case "\$action" in
  start)
    args=(--port "\$port")
    [[ -n "\$graph" ]] && args+=(--graph "\$graph")
    # Detach so the OS launcher returns immediately.
    nohup "\$BIN" "\${args[@]}" > "\$LOG_FILE" 2>&1 &
    disown || true
    ;;
  *)
    printf 'unknown action: %s\n' "\$action" >&2
    exit 1
    ;;
esac
LAUNCHER_EOF
  chmod +x "$LAUNCHER"
}

install_macos() {
  local bin="$1"
  local app_dir="$HOME/Applications/$APP_NAME.app"
  local macos_dir="$app_dir/Contents/MacOS"
  local exe="$macos_dir/$APP_NAME"

  mkdir -p "$macos_dir" "$app_dir/Contents/Resources"

  cat > "$app_dir/Contents/Info.plist" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$APP_NAME</string>
  <key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleExecutable</key><string>$APP_NAME</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSUIElement</key><true/>
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLName</key><string>$BUNDLE_ID</string>
      <key>CFBundleURLSchemes</key>
      <array><string>$SCHEME</string></array>
    </dict>
  </array>
</dict>
</plist>
PLIST_EOF

  # The `.app`'s executable receives the URL as argv[1] via an Apple Event
  # converted by this shim. Uses osascript to intercept the GetURL event.
  cat > "$exe" <<EXE_EOF
#!/usr/bin/env bash
# Launcher shim for $APP_NAME.app — reads the requested turingdb:// URL via
# Apple Events and forwards it to the shared launcher script.
URL=\$(osascript -e 'on open location this_URL
  return this_URL
end open location' 2>/dev/null || true)
if [[ -z "\$URL" && \$# -gt 0 ]]; then URL="\$1"; fi
[[ -n "\$URL" ]] && exec "$LAUNCHER" "\$URL"
EXE_EOF
  chmod +x "$exe"

  # Register with Launch Services so Chrome can find it.
  local lsregister="/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister"
  if [[ -x "$lsregister" ]]; then
    "$lsregister" -f "$app_dir" >/dev/null 2>&1 || true
  fi
  log "macOS: registered $app_dir"
  log "bin:  $bin"
  log "Open once manually (right-click → Open) to clear Gatekeeper if prompted."
}

uninstall_macos() {
  local app_dir="$HOME/Applications/$APP_NAME.app"
  if [[ -d "$app_dir" ]]; then
    rm -rf "$app_dir"
    log "removed $app_dir"
  fi
}

install_linux() {
  local bin="$1"
  local apps_dir="$HOME/.local/share/applications"
  local desktop="$apps_dir/turingdb-launcher.desktop"

  mkdir -p "$apps_dir"
  cat > "$desktop" <<DESKTOP_EOF
[Desktop Entry]
Type=Application
Name=$APP_NAME Launcher
Exec=$LAUNCHER %u
NoDisplay=true
Terminal=false
MimeType=x-scheme-handler/$SCHEME;
DESKTOP_EOF
  chmod +x "$desktop"

  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$apps_dir" >/dev/null 2>&1 || true
  fi
  if command -v xdg-mime >/dev/null 2>&1; then
    xdg-mime default turingdb-launcher.desktop "x-scheme-handler/$SCHEME" >/dev/null 2>&1 || true
  fi
  log "linux: registered $desktop"
  log "bin:   $bin"
}

uninstall_linux() {
  local desktop="$HOME/.local/share/applications/turingdb-launcher.desktop"
  if [[ -f "$desktop" ]]; then
    rm -f "$desktop"
    log "removed $desktop"
  fi
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$HOME/.local/share/applications" >/dev/null 2>&1 || true
  fi
}

main() {
  local os
  os=$(uname -s)

  if [[ $UNINSTALL -eq 1 ]]; then
    case "$os" in
      Darwin) uninstall_macos ;;
      Linux)  uninstall_linux ;;
      *) die "unsupported OS: $os" ;;
    esac
    [[ -f "$LAUNCHER" ]] && rm -f "$LAUNCHER"
    log "done."
    return
  fi

  local bin
  bin=$(resolve_turingdb_bin)
  write_launcher "$bin"

  case "$os" in
    Darwin) install_macos "$bin" ;;
    Linux)  install_linux "$bin" ;;
    *) die "unsupported OS: $os" ;;
  esac

  log "done. Try: open '${SCHEME}://start?port=6666' (or click Launch in the visualizer)."
}

main "$@"
